base: _base.yaml
name: atacom
method: atacom
group: baseline
output_dir: results/arm/peg_insert_cpu/atacom

evaluation:
  training_steps: 200000
  policy_domain_count: 4

method_params:
  policy_ckpt: results/arm/peg_insert_cpu/_policies/shared_atacom_ppo_seed0.pkl
  Kc: 1.0
