base: ../_base.yaml
name: atacom
method: atacom
output_dir: results/arm/peg_insert/baseline/atacom
method_params: {controller_method: atacom, policy_ckpt: results/arm/peg_insert_cpu/_policies/shared_atacom_ppo_seed0.pkl, Kc: 1.0}
