# Ablation: NO CFS retraction.
# environment: center_soft_plane (hybrid center_soft map on plane)
base: ../_base.yaml

level: center_soft_plane
method: mdac_no_retraction
name: arm_impedence_hybrid_center_soft_plane_mdac_no_retraction
output_dir: results/arm/impedence/hybrid/center_soft_plane/ablation/mdac_no_retraction
