base: ../_base.yaml
name: atacom
method: atacom
output_dir: results/humanoid/push_to_line/baseline/atacom
method_params:
  controller_method: atacom
  policy_ckpt_by_suite:
    force_regulation_15n: results/humanoid/box_push/_policies/atacom_force_push_ppo_seed0.pkl
    force_regulation_30n: results/humanoid/box_push/_policies/atacom_force_push_ppo_seed0.pkl
    fixed_stance_push_nominal: results/humanoid/box_push/_policies/atacom_force_push_ppo_seed0.pkl
    fixed_stance_push_ood: results/humanoid/box_push/_policies/atacom_force_push_ppo_seed0.pkl
    unjamming: results/humanoid/box_push/_policies/atacom_unjamming_ppo_seed101.pkl
    walk_and_push: results/humanoid/box_push/_policies/atacom_walk_and_push_ppo_seed0.pkl
  Kc: 1.0
