base: ../_base.yaml
name: pegasusflow
method: pegasusflow
output_dir: results/humanoid/push_to_line/baseline/pegasusflow
method_params: {controller_method: pegasusflow, update_method: avwbfo, wbfo_gamma: 1.0, noise_scheduler_type: s2, noise_shape_fn: linear, noise_decay_fn: exponential, noise_sigma: 1.0, sigma_decay: 0.9, temp_sample: 0.1}
