base: ../_base.yaml
name: standalone_rl
method: standalone_rl
output_dir: results/humanoid/push_to_line/baseline/standalone_rl
method_params:
  controller_method: rl
  policy_ckpt_by_suite:
    force_regulation_15n: results/humanoid/box_push/_policies/fixed_ppo_seed0.pkl
    force_regulation_30n: results/humanoid/box_push/_policies/fixed_ppo_seed0.pkl
    fixed_stance_push_nominal: results/humanoid/box_push/_policies/fixed_ppo_seed0.pkl
    fixed_stance_push_ood: results/humanoid/box_push/_policies/fixed_ppo_seed0.pkl
    unjamming: results/humanoid/box_push/_policies/fixed_ppo_seed0.pkl
    walk_and_push: results/humanoid/box_push/_policies/walk_ppo_seed0.pkl
